### ISSUE TITLE
[ESP32] - 'Guru Meditation Error' when connecting to wifi

### ISSUE THREAD

**Issue by MarcoAbi** [tripflex/captive-portal#9]
Hello, 
I've just built the entire captive portal stack. As I hit "save" (after selecting ssid + password), I have a panic error and ESP32 reboots.

This is the log:
<img width="824" alt="Schermata 2020-01-15 alle 20 07 29" src="https://user-images.githubusercontent.com/3591607/72467686-c030a380-37db-11ea-8aa5-02d7b02a1b5a.png">

Do you have any clue why this is happening?

Thanks
Marco

**Comment by MarcoAbi** [comment]
Hello, someone have any clue why this happens?

Thanks a lot!
Marco

**Comment by tripflex** [comment]
@MarcoAbi please try now that i've updated the https://github.com/tripflex/captive-portal-wifi-setup library that this one relies on. Make sure to do a clean build (remove these libraries from your `deps` directory and rebuild).  There was an issue due to a new protocol feature added in the latest version of the wifi lib that has been resolved in https://github.com/tripflex/captive-portal-wifi-setup

**Comment by tripflex** [comment]
https://github.com/tripflex/captive-portal-wifi-setup/pull/10
